"""empty message

Revision ID: 9e2b61fa9562
Revises: 
Create Date: 2019-02-09 11:26:46.139002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2b61fa9562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=5), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('taken', sa.Boolean(), nullable=True),
    sa.Column('core', sa.Boolean(), nullable=True),
    sa.Column('domain', sa.String(length=5), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
